# Generated by Django 3.2.9 on 2022-11-20 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django.utils.timezone
import panel.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedAuthUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None, unique=True, verbose_name='phone')),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('serial_no', models.CharField(blank=True, default=django.utils.crypto.get_random_string, max_length=100, null=True)),
                ('bgcolor', models.CharField(blank=True, default=panel.models.bgcolor, max_length=10, null=True)),
                ('company', models.CharField(blank=True, default='Studirre', max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, default='416', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='Nairobi', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='Kenya', max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, default='Africa/Nairobi', max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='profiles/')),
                ('role', models.CharField(blank=True, choices=[('employee', 'Employee'), ('admins', 'Admin')], max_length=200, null=True)),
                ('is_deactivated', models.BooleanField(blank=True, default=False, null=True)),
                ('is_online', models.BooleanField(blank=True, default=False, null=True)),
                ('bio', models.TextField(blank=True, default='something about you...', null=True)),
                ('nickname', models.CharField(blank=True, default='Your nickname', max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, default='https://facebook.com/username', max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, default='https://twitter.com/username', max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, default='https://instagram.com/username', max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, default='https://linkedin.com/username', max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('---Select gender---', (('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')))], max_length=6, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'extended_auth_users',
                'db_table': 'extended_auth_user',
            },
        ),
    ]
