# Generated by Django 3.2.9 on 2022-11-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20221120_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='are_you_athletic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extendedauthuser',
            name='are_you_available_for_chat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extendedauthuser',
            name='are_you_married',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extendedauthuser',
            name='are_you_studying',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extendedauthuser',
            name='are_you_working',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='extendedauthuser',
            name='company',
            field=models.CharField(blank=True, default='WeChat', max_length=100, null=True),
        ),
    ]
