# Generated by Django 3.2.9 on 2022-11-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_chatmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='bid_id',
        ),
    ]
