# Generated by Django 3.2.9 on 2022-11-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_remove_chatmodel_bid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='unread_messages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
