# Generated by Django 3.2.9 on 2022-11-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_extendedauthuser_unread_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='single_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
