# Generated by Django 3.2.9 on 2022-11-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_extendedauthuser_single_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='receiver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
