# Generated by Django 3.2.9 on 2022-11-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_extendedauthuser_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedauthuser',
            name='receiver',
        ),
    ]
