# Generated by Django 3.2.9 on 2022-11-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_extendedauthuser_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
