# Generated by Django 3.2.9 on 2022-11-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_extendedauthuser_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
