# Generated by Django 3.2.9 on 2022-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_extendedauthuser_temporary_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='cover_pic',
            field=models.ImageField(blank=True, default='cover.png', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='extendedauthuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='profiles/'),
        ),
    ]
