# Generated by Django 3.2.9 on 2022-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_tweetmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='tweeted_by',
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='retweet_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
