# Generated by Django 3.2.9 on 2022-11-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_likemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='tweet_id',
        ),
    ]
