# Generated by Django 3.2.9 on 2022-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_followmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followmodel',
            old_name='follow_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='followmodel',
            name='follow_on',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
