# Generated by Django 3.2.9 on 2022-11-30 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0021_auto_20221130_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followmodel',
            name='follow_on',
        ),
        migrations.RemoveField(
            model_name='followmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='followmodel',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
