# Generated by Django 3.2.9 on 2022-11-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_auto_20221130_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='extendedauthuser',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
