# Generated by Django 3.2.9 on 2022-11-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_extendedauthuser_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
