# Generated by Django 3.2.9 on 2022-11-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_commentlikemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
