# Generated by Django 3.2.9 on 2022-11-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemodel',
            name='site_email',
            field=models.CharField(blank=True, default='wechat@gmail.com', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='site_name',
            field=models.CharField(blank=True, default='WeChat', max_length=100, null=True),
        ),
    ]
